# Generated by Django 4.2.5 on 2024-06-22 07:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('ifc_link', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.IntegerField(unique=True)),
                ('uuid', models.CharField(default='0', max_length=32)),
                ('discord_refresh_token', models.CharField(default='0', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_link', models.URLField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to='api.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.SmallIntegerField()),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.groupmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_groups', to='api.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='EventUnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='api.eventmodel')),
            ],
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.groupmodel'),
        ),
        migrations.CreateModel(
            name='EventFlightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=4)),
                ('departure_time', models.TimeField(default=django.utils.timezone.now)),
                ('arrival', models.CharField(max_length=4)),
                ('arrival_time', models.TimeField(default=django.utils.timezone.now)),
                ('est_pilots', models.SmallIntegerField()),
                ('act_pilots', models.SmallIntegerField()),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joining_events', to='api.groupmodel')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='api.eventunitmodel')),
            ],
        ),
    ]
