# Generated by Django 4.2.7 on 2024-02-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="uuid",
            field=models.CharField(default="0", max_length=32),
        ),
    ]
