# Generated by Django 4.2.5 on 2024-01-13 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eventjoiningmodel_eventmodel_groupmembersmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
