# Generated by Django 4.2.5 on 2024-07-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eventunitmodel_arrival_eventunitmodel_departure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventunitmodel',
            name='arrival',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='eventunitmodel',
            name='departure',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
