# Generated by Django 4.2.5 on 2024-02-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usermodel_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='uuid',
            field=models.CharField(max_length=32),
        ),
    ]
