# Generated by Django 4.2.5 on 2024-02-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usermodel_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='refresh_token',
            field=models.CharField(default='0', max_length=32),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='uuid',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
