# Generated by Django 4.2.5 on 2024-07-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_eventunitmodel_arrival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventflightmodel',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='eventflightmodel',
            name='act_pilots',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='eventflightmodel',
            name='est_pilots',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
