# Generated by Django 4.2.5 on 2024-02-28 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usermodel_refresh_token_alter_usermodel_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CounterModel',
        ),
        migrations.RemoveField(
            model_name='eventjoiningmodel',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='eventjoiningmodel',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='groupmembersmodel',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='groupmembersmodel',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='groupmodel',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='eventjoiningmodel',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joinings', to='api.eventmodel'),
        ),
        migrations.AddField(
            model_name='eventjoiningmodel',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joining_events', to='api.groupmodel'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.groupmodel'),
        ),
        migrations.AddField(
            model_name='groupmembersmodel',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.groupmodel'),
        ),
        migrations.AddField(
            model_name='groupmembersmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.usermodel'),
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to='api.usermodel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='discord_id',
            field=models.IntegerField(unique=True),
        ),
    ]
