# Generated by Django 4.2.5 on 2024-03-29 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_eventjoiningmodel_duration_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventJoiningModel',
            new_name='EventFlightModel',
        ),
    ]
